# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quarter_Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('franked_mail', models.DecimalField(decimal_places=2, max_digits=20)),
                ('other_services', models.DecimalField(decimal_places=2, max_digits=20)),
                ('personnel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('printing', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_utilities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('supplies', models.DecimalField(decimal_places=2, max_digits=20)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='house_office_spending.Quarter')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_quarters', to='house_office_spending.House_Rep')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('long_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='house_rep',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_reps', to='house_office_spending.State'),
        ),
    ]
